import React from 'react'
import type { Metadata } from 'next'
import './globals.css'
import { GeistSans } from 'geist/font'
import Navbar from '@/components/navbar'
import Footer from '@/components/footer'
import Providers from '@/app/providers'

export const metadata: Metadata = {
 title: 'Deska search engine',
 description: 'Generated by DROP TABLE; team at UJEP Hackithon 2024',
}

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode
}>) {
 return (
  <html lang="en">
   <body
    className={
     GeistSans.className + ' dark:bg-stone-900 dark:text-stone-100 text-stone-900 bg-stone-100'
    }>
    <Navbar />
    <Providers>{children}</Providers>
    <Footer />
   </body>
  </html>
 )
}
